[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_backend"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
primal = "0.3"
rayon = "1.7"
once_cell = "1.19.0"
